name: 'Interactive Inputs'
description: 'Introduce dynamic inputs to your workflows and use them in your actions'
author: 'Leon Silcott <leon@boasi.io>'
inputs:
  title:
    description: 'The title of the interactive inputs form'
    required: false

  interactive:
    description: 'The representation (in yaml) of fields to be displayed'
    required: true
    default: |
      fields:
        - label: random-string
          properties:
            display: Enter a random string
            type: text
            description: A random string up to 20 characters long
            maxLength: 20
            required: false
        - label: choice
          properties:
            display: Select a monitoring tool
            type: select
            description: Available options to chose from
            choices: ["datadog", "sentry", "grafana"]
            required: true

  timeout:
    description: 'The timeout in seconds for the interactive inputs form'
    required: false
    default: "300"

  ngrok-authtoken:
    description: 'The authtoken for ngrok used to expose the interactive inputs form'
    required: true
  
  github-token:
    description: 'The token used to authenticate with GitHub API'
    required: true
    default: ${{ github.token }}
  
  notifier-slack-enabled:
    description: 'Whether to send a notification to Slack about the status of the interative inputs form'
    default: "false"
    required: true

  notifier-slack-thread-ts:
    description: 'The timestamp of the message to reply to in the thread'
    required: false

  notifier-slack-token:
    description: 'The token used to authenticate with Slack API'
    default: "xoxb-secret-token"
    required: true

  notifier-slack-channel:
    description: 'The channel to send the notification to'
    required: true
    default: "#notificaitons"

  notifier-slack-bot:
    description: 'The name of the bot to send the notification as'
    required: false

  notifier-discord-enabled:
    description: 'Whether to send a notification to Discord about the status of the interative inputs form'
    default: "false"
    required: true

  notifier-discord-webhook:
    description: 'The webhook URL used to send the notification(s) to Discord'
    required: true
    default: "secret-webhook"

  notifier-discord-username:
    description: 'The username to send the notification(s) as'
    required: false


runs:
  using: 'node20'
  main: 'invoke-binary.js'
